#!/bin/sh

SWUPDATE_ARGS="-q stable,main-a -q stable,main-b -q stable,full-a -q stable,full-b -q stable,complete"

if [ -r /sys/devices/soc0/soc_id ]; then
    read -r soc_id < /sys/devices/soc0/soc_id
    case "${soc_id}" in
        sama5d31)
            keyrev=$(fw_printenv -n keyrev)
            [ -z "${keyrev}" ] || keyrev="-${keyrev}"
                
            SWUPDATE_ARGS="-H wb50${keyrev}:1.0 ${SWUPDATE_ARGS}"
            ;;

        sama5d36)
            ram_size=$(sed -rn 's/MemTotal:\s*([0-9]+).*/\1/p' /proc/meminfo)

            if [ "${ram_size}" -ge $((128 * 1024)) ]; then
                HW_REV="-H som60x2:1.0"
            else
                HW_REV="-H som60:1.0"
            fi
            SWUPDATE_ARGS="${HW_REV} ${SWUPDATE_ARGS}"
            ;;
    esac
fi
