PYTHON_BTSOCKET_VERSION = v0.3.0
PYTHON_BTSOCKET_SOURCE = $(PYTHON_BTSOCKET_VERSION).tar.gz
PYTHON_BTSOCKET_SITE = $(call github,ukBaz,python-btsocket,$(PYTHON_BTSOCKET_VERSION))
PYTHON_BTSOCKET_LICENSE = MIT
PYTHON_BTSOCKET_LICENSE_FILES = LICENSE
PYTHON_BTSOCKET_SETUP_TYPE = setuptools

$(eval $(python-package))
