AT91BOOTSTRAP3_OVERRIDE_SRCDIR = $(BR2_EXTERNAL_SUMMIT_SOM_PATH)/externals/at91bootstrap3
UBOOT_OVERRIDE_SRCDIR = $(BR2_EXTERNAL_SUMMIT_SOM_PATH)/externals/u-boot-som60
UBOOT_TOOLS_OVERRIDE_SRCDIR = $(BR2_EXTERNAL_SUMMIT_SOM_PATH)/externals/u-boot-som60
TI_K3_R5_LOADER_OVERRIDE_SRCDIR = $(BR2_EXTERNAL_SUMMIT_SOM_PATH)/externals/u-boot-som60

ifeq ($(BR2_SUMMIT_FIPS_7),y)
LINUX_OVERRIDE_SRCDIR = $(BR2_EXTERNAL_SUMMIT_SOM_PATH)/externals/kernel-fips
else ifeq ($(BR2_SUMMIT_FIPS_11),y)
LINUX_OVERRIDE_SRCDIR = $(BR2_EXTERNAL_SUMMIT_SOM_PATH)/externals/kernel-fips-11
else ifneq ($(BR2_TARGET_TI_K3_R5_LOADER),y)
LINUX_OVERRIDE_SRCDIR = $(BR2_EXTERNAL_SUMMIT_SOM_PATH)/externals/kernel
endif

ifeq ($(BR2_LRD_DEVEL_BUILD),y)
include $(call qstrip,$(BR2_EXTERNAL_SUMMIT_RADIO_DEVEL_PATH))/board/radio-local.mk
endif
