AT91BOOTSTRAP3_OVERRIDE_SRCDIR = $(BR2_EXTERNAL_SUMMIT_SOM_PATH)/externals/at91bootstrap3
UBOOT_OVERRIDE_SRCDIR = $(BR2_EXTERNAL_SUMMIT_SOM_PATH)/externals/u-boot-som60
UBOOT_TOOLS_OVERRIDE_SRCDIR = $(BR2_EXTERNAL_SUMMIT_SOM_PATH)/externals/u-boot-som60
TI_K3_R5_LOADER_OVERRIDE_SRCDIR = $(BR2_EXTERNAL_SUMMIT_SOM_PATH)/externals/u-boot-som60

ifeq ($(call qstrip,$(BR2_LINUX_KERNEL_CUSTOM_VERSION)$(BR2_LINUX_KERNEL_CUSTOM_TARBALL)$(BR2_LINUX_KERNEL_CUSTOM_GIT)),)
ifeq ($(BR2_SUMMIT_FIPS_11),y)
LINUX_OVERRIDE_SRCDIR = $(BR2_EXTERNAL_SUMMIT_SOM_PATH)/externals/kernel-fips-11
else
LINUX_OVERRIDE_SRCDIR = $(BR2_EXTERNAL_SUMMIT_SOM_PATH)/externals/kernel
endif
endif

ifeq ($(BR2_LRD_DEVEL_BUILD),y)
include $(call qstrip,$(BR2_EXTERNAL_SUMMIT_RADIO_DEVEL_PATH))/board/radio-local.mk
endif
