################################################################################
#
# toolchain-external-summit-arm
#
################################################################################

TOOLCHAIN_EXTERNAL_SUMMIT_ARM_VERSION = $(call qstrip,$(BR2_TOOLCHAIN_EXTERNAL_SUMMIT_ARM_VERSION))
TOOLCHAIN_EXTERNAL_SUMMIT_ARM_SOURCE := _toolchain-$(call qstrip,$(BR2_TOOLCHAIN_EXTERNAL_SUMMIT_ARM_ID))-$(TOOLCHAIN_EXTERNAL_SUMMIT_ARM_VERSION).tar.gz

ifeq ($(BR2_ARM_EABIHF),y)
TOOLCHAIN_EXTERNAL_SUMMIT_ARM_SOURCE := $(addprefix som60,$(TOOLCHAIN_EXTERNAL_SUMMIT_ARM_SOURCE))
else ifeq ($(BR2_aarch64),y)
TOOLCHAIN_EXTERNAL_SUMMIT_ARM_SOURCE := $(addprefix imx8,$(TOOLCHAIN_EXTERNAL_SUMMIT_ARM_SOURCE))
else
TOOLCHAIN_EXTERNAL_SUMMIT_ARM_SOURCE := $(addprefix wb4x,$(TOOLCHAIN_EXTERNAL_SUMMIT_ARM_SOURCE))
endif

ifeq ($(MSD_BINARIES_SOURCE_LOCATION),laird_internal)
TOOLCHAIN_EXTERNAL_SUMMIT_ARM_SITE = $(SUMMIT_SOM_URI_BASE_INTERNAL)/toolchain/$(TOOLCHAIN_EXTERNAL_SUMMIT_ARM_VERSION)
else
TOOLCHAIN_EXTERNAL_SUMMIT_ARM_SITE = $(SUMMIT_SOM_URI_BASE_ARCHIVE)-$(TOOLCHAIN_EXTERNAL_SUMMIT_ARM_VERSION)
endif

$(eval $(toolchain-external-package))
