#!/bin/sh
# SPDX-License-Identifier: LicenseRef-Ezurio-Clause
# Copyright (C) 2025 Ezurio

die() {
    echo "$1"
    exit 1
}

# Find kernel FIT Image
if [ -f '/boot/kernel.itb' ]; then
    kernel='/boot/kernel.itb'
elif [ -f '/boot/fitImage' ]; then
    kernel='/boot/fitImage'
else
    die 'No kernel image found'
fi

# Retrieve all configurations from FIT Image
confs=$(dumpimage -l ${kernel} | grep -F 'Configuration')

# Find default configuration
default=$(echo "${confs}" | grep -m1 -o 'conf-.*\.dtb')
# Find dtb prefix
prefix=$(echo "${default}" | sed -r 's/-[^-]+\.dtb//')
# Find all parameters
params=$(echo "${confs}" | sed -rn "s/.*${prefix}-(.*)\.dtbo.*/\1/p" | sort -u)

conf=
cconf=$(fw_printenv -n conf)

print_overlays() {
    echo 'Currently set modes/overlays:'
    if [ -z "${cconf}" ]; then
        echo '  No overlays set'
    else
        echo "${cconf}" | tr '#' "\n" | sed -rn "s/${prefix}-(.*)\.dtbo/  \1/p"
    fi
}

print_regdomain() {
    echo 'Currently set regulatory domain:'
    { printf '  '; fw_printenv -n 'RegDomain'; } || \
        die '  No regulatory domain set'
}

case "${1}" in
    '')
        echo "Usage: $0 <mode> [<mode> ...]"
        echo '  <mode> is one or multiple of:'
        echo '  default - remove all overlays'
        echo '  status - print active overlays'
        echo '  regdomain - set regulatory domain for IFX radios'
        echo
        echo 'Available modes/overlays:'
        echo "${params}" | sed 's/^/  /'
        echo
        print_regdomain
        echo
        print_overlays
        exit 1
        ;;

    default)
        # Remove all overlays
        ;;

    status)
        # Print current configuration
        print_overlays
        exit 0
        ;;

    regdomain)
        if [ -n "${2}" ]; then
            fw_setenv 'RegDomain' "${2}"
        else
            print_regdomain
        fi
        exit 0
        ;;

    *)
        # If no parameters are found, exit
        [ -n "${params}" ] || die 'No overlays found'

        . /usr/sbin/boot-rootfs.sh

        # Verify that all parameters are valid and add them into
        # configuration string
        for i in "${@}" ; do
            echo "${params}" | grep -qFx "${i}" || die "Invalid mode ${i}"

            case "${i}" in
                *ifx*)
                    [ -n "$(fw_printenv -n 'RegDomain')" ] || \
                        die 'Regulatory Domain not set for IFX overlay'
                    ;;
            esac

            case "${i}" in
                m2*sdio*)
                    [ "${rootDevType:?}" != 'SD' ] || \
                        die 'M.2 SDIO cannot be used when booting from SD card'
                    ;;
            esac

            conf="${conf}#${prefix}-${i}.dtbo"
        done

        # Add main configuration
        [ -z "${conf}" ] || conf="#${default}${conf}"
        ;;
esac

# Verify that requested configuration is different from current one
[ "${cconf}" != "${conf}" ] || die 'Configuration already set'

# Set new configuration
fw_setenv 'conf' "${conf}"

# Reboot to apply new configuration
reboot
