#############################################################
#
# summit-usersapace-examples
#
#############################################################

SUMMIT_USERSPACE_EXAMPLES_VERSION = local
SUMMIT_USERSPACE_EXAMPLES_SITE = $(BR2_EXTERNAL_SUMMIT_SOM_PATH)/externals/lrd-userspace-examples
SUMMIT_USERSPACE_EXAMPLES_SITE_METHOD = local
SUMMIT_USERSPACE_EXAMPLES_LICENSE = LGPL-2.0+

SUMMIT_USERSPACE_EXAMPLES_DEPENDENCIES = host-pkgconf
SUMMIT_USERSPACE_EXAMPLES_INSTALL_STAGING=YES
SUMMIT_USERSPACE_EXAMPLES_AUTORECONF = YES

SUMMIT_USERSPACE_EXAMPLES_CONF_OPTS =

ifeq ($(BR2_PACKAGE_SUMMIT_USERSPACE_NETWORKMANAGER_EXAMPLES),y)
SUMMIT_USERSPACE_EXAMPLES_CONF_OPTS += --enable-nm-examples
SUMMIT_USERSPACE_EXAMPLES_DEPENDENCIES += summit-network-manager
else
SUMMIT_USERSPACE_EXAMPLES_CONF_OPTS += --disable-nm-examples
endif

ifeq ($(BR2_PACKAGE_SUMMIT_USERSPACE_NETLINK_EXAMPLES),y)
SUMMIT_USERSPACE_EXAMPLES_CONF_OPTS += --enable-nl-examples
SUMMIT_USERSPACE_EXAMPLES_DEPENDENCIES += libnl
else
SUMMIT_USERSPACE_EXAMPLES_CONF_OPTS += --disable-nl-examples
endif

$(eval $(autotools-package))
