#!/bin/sh

# Copyright (c) 2018, Ezurio
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
# OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.
#
# contact: support@ezurio.com

# Firmware Select Utility for WB50n/WB45n/WB40n
#
VERSION=2.21
SELF=${0##*/}
X=/dev/null

# testmode flag/file
TMF=/etc/default/${SELF}.test

# alternate rootfs
ALT_ROOTFS_MOUNT=/mnt/alt_rootfs

# default transfer-list
TRANSFER_LIST_DEFAULT=/tmp/alt_rootfs.transfer-list
TRANSFER_LIST_INCLUDE='
  /etc/ssh/moduli
  /etc/ssh/ssh_host_*key*
  /etc/dropbear
' #^transfer-list


show_usage_info() {
  case "${1}" in
    '') cat << EOF
This utility is mainly useful to:

a.) Switch the kernel-a/b and/or rootfs-a/b images to use upon boot.
  Example usage: [kernel|rootfs]-{a|b} [rootfs|squashfs]
    fw_select                          (..see the current settings)
    fw_select -a                 (..set both kernel-a and rootfs-a)
    fw_select rootfs-b                        (..set just rootfs-b)
    fw_select -a rootfs          (..sets both and configures rootfs-a for booting read/write filesystem)

b.) Copy select files between the alternate rootfs and a current rootfs-a/b.
  Files or paths may be read from a list-file or via the command-line.
  Use 'export' to push from the current to the alternate rootfs.
  Use 'import' to pull from alternate to the current rootfs.
  Use 'access [off]' to just mount or unmount the alternate rootfs.
  (For more details and for using a list-file, do: --transfer help)
  Usage: --transfer {access [off]}
         --transfer {import|export [<path/to/list-file> | -- <files..>]}
  Examples:
    fw_select --transfer access off (..unmount the ${ALT_ROOTFS_MOUNT})
    fw_select --transfer export -- pat  for mtd in /sys/class/mtd/mtd*/type
  do
    [ -f "${mtd}" ] || continue
h/file1 path/file2
             (..push the two path/files to ${ALT_ROOTFS_MOUNT})

c.) Restore default bootcmd and bootargs from the u-boot image.
  Without given arg, just restore bootcmd, bootargs and dependent variables.
  With '...' the extracted defaults are also displayed.
  With 'erase' the u-boot_env is erased, defaults restored on reboot.
  Usage: --default [...|erase]
  Example:
    fw_select --default            (..restore bootcmd and bootargs)

d.) Set kernel loglevel value in bootargs, or restore it.
  Without a given value, then a default value from the u-boot image is used.
  Usage: --loglevel=[0-8]
  Example:
    fw_select --loglevel                   (..set default loglevel)

e.) Show details of flash memory layout and versions of all detected images.
  Usage: --show

EOF
    ;;

    transfer) cat << EOF
This option allows copying select files between the two root-filesystems.
  (such as settings, profiles, certs, keys, etc...)

Note, paths/files included by default: ${TRANSFER_LIST_INCLUDE}
Use 'import' to copy from the other filesystem to the current filesystem.
Use 'export' to copy from the current filesystem to the other filesystem.
  Additional folders/files may be copied (to mirrored locations) by using a
  specified 'transfer-list' file, or if '/tmp/alt_rootfs.transfer-list' file
  exists. Format is simply a list of paths ('#' comment lines are ignored).

  Sample listing of paths or files:
    /etc/summit/profiles.conf
    /etc/network/interfaces
    /etc/ssl/*.cer
    /etc/ssl/*.crt
    /etc/ssl/*.der
    /etc/ssl/*.key
    /etc/ssl/*.p7*
    /etc/ssl/*.p8*
    /etc/ssl/*.p12
    /etc/ssl/*.pac
    /etc/ssl/*.pem
    /etc/ssl/*.pfx
    /etc/ssl/*.spc
    /root/.ssh

  Usage: --transfer import|export [<path/to/list-file> | -- <files..>]
  Examples:
    fw_select --transfer import /root/mylist.txt
             (..pull-in default items and also items in mylist.txt)

    fw_select --transfer export -- /path/file1 /path/file2
             (..push default items and also file1 and file2)

Use 'access' to just mount the other filesystem at ${ALT_ROOTFS_MOUNT}.
Use 'access off' to umount the other filesystem at ${ALT_ROOTFS_MOUNT}.
  These operations contain several sanity checks for the NAND ubifs.
  And are performed automatically when using import or export.
  Usage: --transfer access [off]
  Example:
    fw_select --transfer access off     (..unmount ${ALT_ROOTFS_MOUNT})

EOF
    ;;

    options) cat << EOF
  --transfer*    copy from/to alt-rootfs '--transfer help'
  --loglevel*    restore or set new value '--loglevel=[0-8]'
  --default*    restore default u-boot_env variables '--default help'
  --usage    see detailed usage info and a few examples
  --show    flash memory layout and images detected
  --tm*    enable persistent testmode, or disable '--tm off'
  *-a    set kernel/rootfs to use '-a' images
  *-b    set kernel/rootfs to use '-b' images
  --    affirm executable, version and mode
EOF
    ;;

    default) cat << EOF
This option allows restoring the u-boot_env bootcmd and bootargs.
  (the defaults are extracted from the u-boot binary image)

Use '...' to also see the defaults from the image.

Use 'erase' to completely restore all of u-boot_env to defaults, upon reboot.
  Note: the current ethaddr value will be lost, so it is necessary to manually
  write this value back after rebooting.

  Usage: --default [...|erase]
  Example:
    fw_select --default ...           (..restore/show bootcmd+args)

EOF
esac
}

# set testmode if the flag/file exists
test -f "${TMF}" && tm='printf' || tm=
grep -sqF 'verbose' "${TMF}" && set -x

# set some commands in testmode so won't do any writes
reboot="${tm} reboot"
flash_erase="${tm} flash_erase"
fw_setenv="${tm} fw_setenv"
fw_printenv=fw_printenv

exit_error() {
  echo "${1:+  ...$@}"
  exit 1
} >&2

rm -f /tmp/incompatible_u-boot_env

[ -f /etc/fw_env.config ] || \
  exit_error "  ...missing: /etc/fw_env.config"

eval "$( $fw_printenv -n updated_% 2>${X} |
      grep -o "at91bs=.\|u_boot=.\|kernel=.\|rootfs=." )"

# check/parse description-of-machine: <string> and determine settings
x=$( grep -s 'Workgroup Bridge' /proc/device-tree/model \
  || sed -nr 's/Hardware[ \t:]*(.*)/\1/p' /proc/cpuinfo )
case "${x}" in
  *'Workgroup Bridge 40N'*)
    ### arch/arm/mach-at91/board-wb40n.c
    wb=wb40n
    ;;
  *'Workgroup Bridge 45N'*)
    ### arch/arm/mach-at91/board-dt.c
    wb=wb45n
    ;;
  *'Workgroup Bridge 50N'*)
    ### arch/arm/boot/dts/wb50n.dts
    wb=wb50n
    ;;
  *)
    ### architecture unknown...
    [ -z "${x}" ] || echo ": ${x}" >&2
    grep -om1 ': ARM' /proc/cpuinfo >&2 \
      || sed -n '/name/{s/model name.*\(: .*\)/\1/p;q}' /proc/cpuinfo >&2
    exit_error "unsupported, must be Summit WB platform"
    ;;
esac

scan_partitions() {
  # find settings for imageset a/a, add to get b/b

  [ -z "${UBM}" ] || return 0

  for mtd in /sys/class/mtd/mtd*/type
  do
    [ -f "${mtd}" ] || continue

    read -r type < "${mtd}"
    [ "${type}" = "nand" ] || continue

    mtd=${mtd%/*}

    read -r name < "${mtd}/name"
    read -r size < "${mtd}/size"

    mtd=${mtd##/sys/class/mtd/mtd}
    [ "${mtd}" -ne 0 ] || addr=0
    case "${name}" in
      kernel-a) KIA=$( hexify "${addr}" ) KIS=$(hexify "${size}") KIP=${mtd} ;;
      rootfs-a) RIP=${mtd} ;;
    esac
    addr=$((addr+size))
  done
  UBM="$( fw_printenv bootcmd |sed -nr 's/.*nand read\s+(\w+).*/\1/p' )"

  for i in ${UBM:-0} ${KIP:-0} ${KIA:-0} ${KIS:-0} ${RIP:-0}
  do
    [ $((i)) -eq $((i)) ] || exit_error "cannot determine mapping for kernel/rootfs"
  done
}

# ask user for confirmation with timeout
# args: <prompt> <timeout>
# if read with timeout not supported by shell assume 'y'
ask() {
  # pull all chars from the input buffer
  # shellcheck disable=SC3045
  read -r -t 0 -n 1000 2>${X} || [ $? -eq 1 ] || return 0
  # shellcheck disable=SC3045
  if read -r -p "${1} [y/N ..${2}s]" -t "${2}" -n 1 && [ "${REPLY}" = y ] ; then
    echo y
    return 0
  else
    echo n
    return 1
  fi
}

# special functions to evaluate arithimetic expressions
hexify() { printf "0x%08x" $((${1:-0})); }

bootcmd_x() {
  scan_partitions

  [ -z "${BC_kia}" ] || return 0

  # parse formatted kernel-image-address and also copy any boot commands
  eval "$($fw_printenv -n bootcmd | sed -nr "s/.*nand read\s+\w+\s+(\w+)\s+\w+[; \t]*(.*)/BC_kia=\1; BC_boot='\2'/p")"

  BC_kia=$( hexify "${BC_kia}" )

  if [ $((BC_kia)) -eq 0 ] || \
    { [ "${BC_kia}" != "${KIA}" ] && [ "${BC_kia}" != "$(hexify "${KIA}+${KIS}")" ]; }
  then
    [ "auto" = "${1}" ] && return 0
    echo "  ...incompatible bootcmd set in u-boot_env" >&2
    touch /tmp/incompatible_u-boot_env
    BC_kia=$( hexify )
    return 1
  fi
  return 0
}

bootargs_x() {
  [ -z "${BA_mtd}" ] || return 0

  # parse the rootfs mtd partition number
  BA_mtd=$($fw_printenv -n bootargs | sed -nr 's/.*ubi.mtd=([0-9]+).*/\1/p')

  if [ -z "${BA_mtd}" ]
  then
#    [ "auto" = "${1}" ] && return 0
    echo "  ...incompatible bootargs set in u-boot_env" >&2
    touch /tmp/incompatible_u-boot_env
    BA_mtd=0
    return 1
  fi
  return 0
}

kernel_ab() {
  # report the kernel partition currently set... (pseudo-static)
  bootcmd_x || { echo '?'; return; }
  [ $((BC_kia)) -eq $((KIA)) ] && echo a || echo b
}

rootfs_ab() {
  # report the rootfs partition currently set... (pseudo-static)
  bootargs_x || { echo '?'; return; }
  [ $((BA_mtd)) -eq $((RIP)) ] && echo a || echo b
}

kernel_x() {
  # report the kernel partition being used... (pseudo-static)
  bootcmd_x || { echo 0; return; }
  [ $((BC_kia)) -eq $((KIA)) ] && echo $((KIP)) || echo $((KIP+1))
}

rootfs_x() {
  # report the rootfs partition being used... (actual)
  sed -nr 's/.*ubi.mtd=([0-9]+).*/\1/p' /proc/cmdline
}

display_release() {
  if [ "${2}" = full ]; then
    if [ -f "${1}/etc/os-release" ]; then
      sed -nr 's/PRETTY_NAME="(.*)"/\1/p' "${1}/etc/os-release"
    else
      cat "${1}"/etc/*-release
    fi
  else
    if [ -f "${1}/etc/os-release" ]; then
      sed -nr 's/BUILD_ID=(.*)/\1/p' "${1}/etc/os-release"
    else
      grep -som1 '[^ ]*$' "${1}"/etc/*-release
    fi
  fi
}

current_configuration() {
  scan_partitions
  display_release '' full
  [ $(($(rootfs_x))) -eq $((RIP)) ] && ab=a || ab=b
  echo " -> $(uname -sr) on rootfs-${ab}"
  echo "     ...mismatched kernel: $(ls -d /lib/modules/*)" | grep -v "$(uname -r)"
  echo

  if [ -d ${ALT_ROOTFS_MOUNT} ] && grep -qF ${ALT_ROOTFS_MOUNT} /proc/mounts
  then
    echo "${ALT_ROOTFS_MOUNT} is accessible:"
    echo "  rootfs-$(alt_rootfs): $(display_release ${ALT_ROOTFS_MOUNT})"
  fi

  if [ -n "${at91bs}${u_boot}${rootfs}${kernel}" ]
  then
    echo "updated_%"
    [ -z "${at91bs}" ] || echo "  at91bs"
    [ -z "${u_boot}" ] || echo "  u_boot"
    [ -z "${kernel}" ] || echo "  kernel"
    [ -z "${rootfs}" ] || echo "  rootfs"
  fi
  echo "bootup:"
  echo "  kernel-$(kernel_ab)"
  echo "  rootfs-$(rootfs_ab)"
}

alt_rootfs() {
  [ $(($(rootfs_x))) -eq $((RIP)) ] && arip=$((RIP+1)) || arip=$((RIP))
  #
  # args: <un/mount>
  case "${1}" in
    '')
      # indicate alt_rootfs is a/b
      [ $((arip)) -eq $((RIP)) ] && echo a || echo b
      ;;

    u*)
      # try to unmount
      unset rv x

      [ -d ${ALT_ROOTFS_MOUNT} ] && grep -qF ${ALT_ROOTFS_MOUNT} /proc/mounts || \
        return 1

      umount ${ALT_ROOTFS_MOUNT} || return 1
      x="unmounted"

      for i in /sys/class/ubi/ubi*/mtd_num
      do
        [ -f "${i}" ] || continue

        read -r num < "${i}"

        if [ "${num}" -eq "${arip}" ]; then
          i=${i%/mtd_num}
          i=${i##/sys/class/ubi/}
          ubidetach -m "${num}" && x="${x} (${i} detached)" || rv=1
          break
        fi
      done
      unset i

      rmdir ${ALT_ROOTFS_MOUNT} && x="${x} ${ALT_ROOTFS_MOUNT}" || rv=1

      echo "${x}"
      return ${rv}
      ;;

    m*)
      # try to mount
      # check if mount directory exists
      if [ -d ${ALT_ROOTFS_MOUNT} ]; then
        # check if already mounted
        if ! grep -qF ${ALT_ROOTFS_MOUNT} /proc/mounts; then
          echo "  %s is n/a" ${ALT_ROOTFS_MOUNT}
          return 1
        fi

        echo "  ...already attached and mounted"
        return 0
      fi

      # create mount directory
      mkdir -p ${ALT_ROOTFS_MOUNT}
      # attach ubi
      n=$(ubiattach -m "${arip}" | sed -r 's/.*ice number ([0-9]+).*/\1/') 2>${X}
      if [ -z "${n}" ] || [ "$(cat "/sys/class/ubi/ubi${n}/volumes_count")" -ne 1 ]
      then
        echo "  ...unable to mount /dev/mtd${arip}"
        echo " (try: '--transfer access off')"
        [ -z "${n}" ] || ubidetach -m "${arip}"
        rmdir ${ALT_ROOTFS_MOUNT}
        return 1
      fi

      if ! mount -t ubifs "/dev/ubi${n}_0" ${ALT_ROOTFS_MOUNT} 2>${X}
      then
        echo "  ...unable to mount /dev/mtd${arip}"
        ubidetach -m "${arip}"
        rmdir ${ALT_ROOTFS_MOUNT}
        return 1
      fi

      echo "mounted /dev/mtd${arip} at ${ALT_ROOTFS_MOUNT}"
      ;;
  esac
}

# note: whitespace in the path/file name is not handled
# args: <source> <target> <item-path/file>
cp_dprf() {
  src_file=${1}${3#/}

  if [ -e "${src_file}" ]
  then
    ${tm:-:} "  ${src_file}" && ${tm:+return}
    tar -cC "${1}" "${3#/}" | tar -xvC "${2}" | sed 's/^/  \//'
  else
    echo "? ${src_file}"
  fi
}

transfer_system_files() {
  [ "${1}" = -v ] && { shift; echo "transferring system settings"; }

  alt_rootfs m || return 1

  [ "${1}" != '/' ] && st=from || st=to

  s=${1};
  t=${2};
  shift 2
  echo

  # combine items from a transfer-list file and/or any given via command-line
  # if assumed file 'alt_rootfs.transfer-list' exists then include defaults
  # note - fw_update may create/append to this file; it can also be empty
  f=${1:-${TRANSFER_LIST_DEFAULT}}
  [ "${f}" = ${TRANSFER_LIST_DEFAULT} ] || TRANSFER_LIST_INCLUDE=
  [ "${f}" != '--' ] || f=

  # only accept given items after a double dash
  while [ -n "${1}" ] && [ "${1}" != '--' ]; do shift; done
  [ "${1}" != '--' ] || shift

  # read file
  if [ -s "${f}" ]; then
    # remove comments and empty lines, then trim leading/trailing whitespace
    rf=$(sed -r '/^\s*#/d;/^\s*$/d;s/\s*//' "${f}")
  else
    [ -z "${f}" ] || echo "warning - transfer-list file n/a: ${f}";
  fi

  # compile transfer-list w/o duplicates
  # then iterate over items for transfer
  tls=
  for i in ${TRANSFER_LIST_INCLUDE} ${rf} "$@"
  do
    # skip if item is already in the list
    [ "${tls#* "${i}" }" = "${tls% "${i}" *}" ] || continue

    # add item to the list
    tls="${tls} ${i}"
  done

  if [ -n "${tls# *}" ]; then
    echo "copying ${st} rootfs-$(alt_rootfs)"
    for i in ${tls}; do
      cp_dprf "${s}" "${t}" "${i}"
    done
    echo
  fi

  alt_rootfs u
}

fipsOnAlt() {
  scan_partitions
  alt_rootfs m >${X} || return 1

  [ -f ${ALT_ROOTFS_MOUNT}/usr/sbin/fipsInit.sh ] && echo fips || echo none

  alt_rootfs u >${X}
}

switch_bootargs() {
  case "${1}" in
    rootfs)
      # read/write filesystem mounting
      bootargs=$( $fw_printenv -n bootargs | sed "s/rootfstype=.*\ /rootfstype=ubifs\ root=ubi0:rootfs\ /")
      $fw_setenv bootargs "${bootargs}"
      ;;
    --help|-h|?)
      echo "Options:"
      echo "rootfs - will update bootargs to boot read/write filesystem"
      ;;
    *) # do nothing
      ;;
  esac
}

nand_grep() {
  nanddump --bb=skipbad --omitoob --quiet "${2}" 2>${X} | grep -Eaom1 "${1}"
}

# main
case "${1}" in
  --transfer*)
    ## copy from/to alt-rootfs '--transfer help'
    if bootcmd_x
    then
      case "${2}" in
        access)
          # make the alternate rootfs accessible or not [<off>]
          if [ "off" != "${3}" ]; then alt_rootfs m; else alt_rootfs u; fi
          ;;
        export|push)
          # push select files to alternate rootfs
          shift 2 && transfer_system_files / ${ALT_ROOTFS_MOUNT}/ "$@"
          ;;
        import|pull)
          # pull select files to current rootfs
          shift 2 && transfer_system_files ${ALT_ROOTFS_MOUNT}/ / "$@"
          ;;
        '')
          # assume 'push/pull' based on rule
          [ -n "$rcS_" ] && transfer_system_files -v ${ALT_ROOTFS_MOUNT}/ /
          { [ -n "${rootfs}" ] && transfer_system_files -v / ${ALT_ROOTFS_MOUNT}/; } || \
            { echo '?'; exit_error; }
          ;;
        *)
          # show relevant usage/help
          show_usage_info transfer
          ;;
      esac
    fi
    ;;

  --loglevel*)
    # restore or set new value '--loglevel=[0-8]'
    IFS='='
    set -- "${1}"
    if [ $# -ne 2 ]; then
      set -- "$(nand_grep 'loglevel=[0-8]' /dev/mtd1)"
    fi
    unset IFS

    [ "${2}" -eq "${2}" ] 2>${X} && loglevel=${2} || loglevel=4

    # set loglevel with given value or default value from u-boot or assume '4'
    args=$( $fw_printenv -n bootargs | sed -r "s/(loglevel=)./\1${loglevel}/" )
    $fw_setenv bootargs "${args}"  && echo "set loglevel=${loglevel}"
    ;;

  --default*)
    ## restore default u-boot_env variables '--default help'
    case "${2}" in
      erase)
        # set all defaults by erasing u-boot_env
        echo "erasing u-boot_env to restore defaults, then will reboot"
        $fw_printenv ethaddr 2>${X} \
          | sed 's/.*/\nWarning: this will remove the current &/;s/=/ /'

        ask -p "  Are you sure?" 5 || exit_error aborted

        ### erase procedure for redundant u-boot_env
        { $flash_erase -q /dev/mtd3 0 0 && $flash_erase -q /dev/mtd2 0 0 && $reboot; } \
          || exit_error "failed to erase u-boot_env"
        ;;
      ''|'...')
        # set default bootcmd/args and dependents from u-boot image
        echo reading /dev/mtd1

        # retrieve default environment from u-boot image into /tmp/u-boot
        # shellcheck disable=SC2016
        nanddump --bb=skipbad --omitoob --quiet /dev/mtd1 | strings | \
          sed -nr '/^\w+=[a-zA-Z0-9\.\(\) \/,;:=_-]+$/,${p;/^\w+=[a-zA-Z0-9\.\(\) \/,;:=_-]+$/!q}' \
          >/tmp/u-boot
        [ -s /tmp/u-boot ] || { rm -f /tmp/u-boot; \
          exit_error "unable to get default settings from image at /dev/mtd1"; }
        # delete last line from environment file as it is always junk
        sed -i '$d' /tmp/u-boot

        # print retrieved defaults from u-boot image
        [ '...' != "${2}" ] || \
          printf "\nu-boot: (defaults)\n"; cat /tmp/u-boot

        printf "\nrestoring...\n"
        # extract bootcmd and bootargs into new environment
        grep -E '^bootcmd=|^bootargs=' /tmp/u-boot > /tmp/u-boot_new

        # extract run command into the new environment, if present
        runcmd=$(sed -nr "s/bootcmd=.*run ([^;]+).*/\1/p" /tmp/u-boot)
        [ -z "${runcmd}" ] || \
          grep -E "^${runcmd}=" /tmp/u-boot >> /tmp/u-boot_new

        # set boot commands from default environment
        $fw_setenv -s /tmp/u-boot_new

        # delete temporary files
        rm -f /tmp/u-boot /tmp/u-boot_new

        # show the new environment
        printf '\nu-boot_env: (fw_printenv)\n'
        $fw_printenv
        ;;
      *)
        # show relevant usage/help
        show_usage_info default
        ;;
    esac
    ;;

  --fips)
    fipsOnAlt
    ;;

  --usage)
    ## see detailed usage info and a few examples
    show_usage_info
    exec ${0} -h
    ;;

  --show)
    ## flash memory layout and images detected

    scan_partitions
    kip=$(kernel_x)
    rip=$(rootfs_x)
    addr=0

    echo "${wb} - flash memory"
    echo "  mtd     address     size      description"

    for mtd in /sys/class/mtd/mtd*/type
    do
      [ -f "${mtd}" ] || continue

      read -r type < "${mtd}"
      [ "${type}" = "nand" ] || continue

      mtd=${mtd%/*}

      read -r name < "${mtd}/name"
      read -r size < "${mtd}/size"

      mtd=${mtd##/sys/class/mtd/mtd}
      vers=' '
      ap='  '
      case "${name}" in
        *tstrap|at91bs)
          vers=$(nand_grep '[0-9]+\.[0-9]+\.[0-9]+[a-z0-9.-]*' "/dev/mtd${mtd}")
          ;;
        u-boot )
          vers=$(nand_grep '[0-9]{4}\.[0-9]{2}[a-z0-9.-]*' "/dev/mtd${mtd}")
          ;;
        kernel*)
          [ $((mtd)) -ne $((kip)) ] || ap='->'
          vers=$(nand_grep '[0-9]+\.[0-9]+\.[0-9]+[a-z0-9.-]*' "/dev/mtd${mtd}")
          ;;
        rootfs*)
          if [ $((mtd)) -eq $((rip)) ]; then
            ap='->'
            vers=$(display_release)
          elif alt_rootfs m >${X}; then
            vers=$(display_release ${ALT_ROOTFS_MOUNT})
            alt_rootfs u >${X}
          fi
          ;;
      esac
      printf " %s% 2d:  0x%08x  0x%08x  %-12s %s\n" "${ap}" "${mtd}" "${addr}" "${size}" "${name}" "${vers}"
      addr=$((addr+size))
    done
    echo
    current_configuration
    ;;

  --tm*)
    ## enable persistent testmode, or disable '--tm off'
    { [ "off" = "$2" ] && rm -fv "${TMF}"; } || { mkdir -p "${TMF%/*}"; echo "${2}" >"${TMF}"; }
    exec ${0} --
    ;;

  *-a)
    ## set kernel/rootfs to use '-a' images
    bootcmd_x auto
    if [ "${1}" != "${1#kernel*}" ] || [ "-a" = "${1}" ]
    then
      kia=$( hexify "${KIA}" )
      $fw_setenv bootcmd "nand read ${UBM} ${kia} ${KIS}; ${BC_boot:-}" \
        && echo "set kernel-a"
    fi
    bootargs_x
    if [ "${1}" != "${1#rootfs*}" ] || [ "-a" = "${1}" ]
    then
      mtd=$((RIP+0))
      bootargs=$($fw_printenv -n bootargs |sed "s/ubi.mtd=./ubi.mtd=${mtd}/")
      $fw_setenv bootargs "${bootargs}" && echo set rootfs-a
      switch_bootargs "${2}"
    fi
    ;;

  *-b)
    ## set kernel/rootfs to use '-b' images
    bootcmd_x auto
    if [ "${1}" != "${1#kernel*}" ] || [ "-b" = "${1}" ]
    then
      kia=$( hexify "${KIA}+${KIS}" )
      $fw_setenv bootcmd "nand read ${UBM} ${kia} ${KIS}; ${BC_boot}" \
        && echo set kernel-b
    fi
    bootargs_x
    if [ "${1}" != "${1#rootfs*}" ] || [ "-b" = "${1}" ]
    then
      mtd=$((RIP + 1))
      bootargs=$( $fw_printenv -n bootargs |sed "s/ubi.mtd=./ubi.mtd=${mtd}/" )
      $fw_setenv bootargs "${bootargs}" && echo set rootfs-b
      switch_bootargs "${2}"
    fi
    ;;

  --|--version)
    ## affirm executable, version and mode
    echo "${SELF} v${VERSION}  ${tm:+\[testmode\]}"
    exit 0
    ;;

  --help|-h)
    # quick help
    echo "Quick reference...  (*askerisk denotes variations of an option)"
    echo "Options:"
    show_usage_info options
    printf "Usage:\n  fw_select <option>\n"
    ;;

  '')
    ## show current settings
    current_configuration
    ;;

  *)
    # error
    exit_error "unknown option specified"
    ;;
esac
rv=$((rv+$?))

if [ -f /tmp/incompatible_u-boot_env ]
then
  cat >&2 << EOF
incompatible u-boot_env detected
 check u-boot_env settings:
   ${SELF} --show
 restore specific defaults or erase/restore all:
   ${SELF} --default help
EOF
  exit 1
fi

${tm:-:} "\n  testmode active\n  ...remove '${TMF}'\n     or try: '--tm off'\n" >&2
exit ${rv}
