#!/bin/sh
# Copyright (c) 2025, Ezurio
# SPDX-License-Identifier: LicenseRef-Ezurio-Clause
#
# Firmware Update Utility for WB50n/WB45n/WB40n Legacy

VERSION=3.0.0
SELF=${0##*/}
X=/dev/null
M=\-\>\|\<\-

# testmode flag/file
TMF=/etc/default/$SELF.test

# binary image files
AT91BS_IMG=at91bs.bin
U_BOOT_IMG=u-boot.bin
KERNEL_IMG=kernel.bin
ROOTFS_IMG=rootfs.bin

FWUL=/tmp/fw.txt
FWU_ERR=/tmp/fwu.err
FWU_FIFO=/tmp/fwu.fifo
FWU_MD5=/tmp/fwu.fmd5
FWU_UBIFS=/tmp/fwu.ubifs
FWU_TRANSFER_LIST=/tmp/alt_rootfs.transfer-list
TMP_DL=/tmp/fwu.file

# ucs dgram sendto port
# format is xml or json
NS_PORT=2012
NS_FORMAT=xml

errors=0

# cleanup function to remove temporary files
cleanup_temp_files() {
  rm -f "$FWUL" \
    "$FWU_ERR" \
    "$FWU_FIFO" \
    "$FWU_MD5" \
    "$FWU_UBIFS" \
    "$FWU_TRANSFER_LIST" \
    "$TMP_DL"
}
trap cleanup_temp_files EXIT TERM INT

show_usage_info() {
  [ -z "$1" ] && cat << --Usage-Info--
This utility performs flash memory updates of WB firmware using:
  a) locally attached USB Flash Drive or other mounted media, via file copy
  b) anonymous remote server via wget:  (https:// -or- http:// -or- ftp://)

Optionally, the 'fw_select' utility can be used to:
  a) show current settings and image details
  b) switch bootup of kernel-a/b and rootfs-a/b
  c) transfer files from or to the alternate rootfs
  d) restore/recover u-boot_env defaults

Using 'fw_update':
  A firmware-update-list file is used, containing each image md5, name, size.

  Each image source is evaluated to ensure it exists and is of non-zero length.
  And the MD5sum of the image is compared to the stored value in Flash to avoid
  unnecessary updating.  (use '-f' flag to avoid prompt for overwriting)

  Redundant kernel/rootfs-a/b flash partitions are expected to exist, and will
  be alternately targeted for updating, then selected for next bootup.

  If the kernel/rootfs update does not successfully complete, then you should
  be able to re-attempt the update again.  (use 'fw_select' for more options)
  Note: the at91bs and u-boot images should only be updated if very necessary.

  Use the '-c' flag, to also check each flashed image update, for matched md5.

  The '-f' flag will assume image overwrites and avoid pings to the server.

  Using '-d', allows just downloading the update-list, for optional editing.

  The update procedure may be controlled via the firmware-update-list, by also
  including lines with any flag options and an optional shell script-&-args.
                                      (for more info, try '--usage ${FWUL##*/}')
Extended operations:
  Automatic after updating:  notify, transfer, and reboot

  Disable extended operations with the '-x' flag.  For control of a specific
  operation, append first-letter like: '-x[ntr]'.

  If file '/tmp/alt_rootfs.transfer-list' exists,
  then 'fw_select --transfer push' is performed.  (see 'fw_select' for detail)

  If updating remotely, notification is sent back to the serving host:$NS_PORT.
  This UDP datagram is $NS_FORMAT formatted w/ ethaddr, build, status, message.
  The status word is one of: update_(failure|pending|success)

Example usage:                                   (to see options, try '-h')
  fw_update /media/usb0/<path/to>/${FWUL##*/}
           (..use local method)

  fw_update ftp://<server/path/to/>/${FWUL##*/}
           (..use remote ftp method)

  fw_update -xt http://<server/path/to/>/${FWUL##*/}
           (..use remote http method, and skip transfer)

  fw_update -xr --url http://<server/path> /root/fw.txt
           (..use local list w/remote http method, no reboot)

  fw_update -f -c -xnr <path/to>/${FWUL##*/}
           (..force, check, transfer, but dont notify or reboot)

  fw_update -d http://<server/path/to/>/${FWUL##*/}
           (..download the update-list, then can edit $FWUL and re-run )

  fw_update --url http://http://<server/path>
           (..re-run using $FWUL and with applied images server link )

  fw_update http://<server>/fw.txt?nsap=<notification_server>:<port_no>
           (..use remote http method and specify non-default notification server)
End
--Usage-Info--

  [ -n "$1" ] && cat << --Usage-Info--
A firmware-update-list file '${FWUL##*/}' is always required for operation.
  It may be any name with a '.txt' extension, and is processed as $FWUL.

  The first line of a firmware-update-list may have '# <wb-target-version>'
  and a check is then made to match the WB platform for the firmware-update.

  Each listed image may include the absolute, or a relative, url/path/name.
  Specific images or lines may be commented-out w/'#', and thus skipped over.

  A section for a 'transfer-list' is defined with a comment using this word,
  and ending with a blank line. See 'fw_select --transfer help' for details.

  Flags in the firmware-update-list are used in lieu of any on the cmdline.
  After updating the images, an optional shell invocation plus args, is run.

Format of ${FWUL##*/}:
  # <wb??n-target-version>
  # comment lines begin with '#' char
    <md5sum>  <[url/][path/]image>  [<bytes>]
    shell <invocation and args to run>
    flags <cmdline flags to apply>

Example ${FWUL##*/}:
  # wb50n-summit_fips-3.4.1.105
  # example of a wb50n update with bootstrap disabled
  # ab8d615dac1be37e71b42d1c29f10a9d  at91bs.bin  11444
    0da1ebd394521581857702facf305129  u-boot.bin  359028
    06ea0dfeb5b0d9215ac74c0da2b18af1  kernel.bin  2150318
    6bcea984d8994f7a60ca5ec1d9438413  rootfs.bin  25034752

  # no auto reboot and force updating
    flags -xr -f

  # run a user script on the WB as part of the post-update step
    shell /root/my_script -a -b -c

  # transfer-list
    /etc/summit/profiles.conf
    /etc/network/interfaces
    /root/my_file
    /usr/local/bin/my_app

End
--Usage-Info--
}

# shellcheck disable=SC2329
# function call constructed in -n option
xml_notification() {
  name=${wb:-wb}
  [ -n "$1" ] && status="<status>$1</status>"
  [ -n "$2" ] && message="<message>$2</message>"
  cat <<__END-OF-XML-NOTIFICATION-BLOCK
  <$name id=$(grep -so ..:. /sys/class/net/eth0/address 2>"$X")>
  <version>$(grep -m1 -so '[^ ]*$' /etc/*-release 2>"$X")</version>
    $status
    $message
  </$name>
__END-OF-XML-NOTIFICATION-BLOCK
}


# shellcheck disable=SC2329
# function call constructed in -n option
json_notification() {
  name=${wb:-wb}
  [ -n "$1" ] && status="\"status\": \"$1\","
  [ -n "$2" ] && message="\"message\": \"$2\""
  cat <<__END-OF-JSON-NOTIFICATION-BLOCK
  {\"$name\": {
    \"mac\": \"$(grep -so ..:. /sys/class/net/eth0/address 2>"$X")\",
    \"version\": \"$(grep -m1 -so '[^ ]*$' /etc/*-release 2>"$X")\",
    $status
    $message
  }
__END-OF-JSON-NOTIFICATION-BLOCK
}

ask() {
  read -t 1 -n 1000
  if read -p "$1 [y/N ..$2s]" -rst $2 -n 1 && [ "$REPLY" = y ] ; then
    echo y
    return 0
  else
    echo n
    return 1
  fi
}

exit_error() {
  $x_notify && $0 --n "$host" update_failure
  echo "${1:+  ...$@}" >&2
  exit 1
} >&2

verbose() {
  print_nl=false
  # check if 2 args, use first arg as bool. If true, print newline
  [ $# -eq 2 ] && [ "$1" = true ] && print_nl=true && shift
  $o_verbose && printf "%s" "$@" || :
  [ $print_nl = true ] && printf "\n"
} 2>$X

await() {
  eto=$2
  while [ -f /proc/$1/comm ] && [ "$eto" -gt 0 ]
  do
    eto=$((eto-1))
    $o_verbose && printf "%s" "$3"
    sleep 1
  done &
} 2>$X

# check testmode file/flag
test -f "$TMF" && tm=echo\ -e || tm=
grep -sq verbose "$TMF" && set -x

# check/parse description-of-machine: <string> and determine settings
x=$( grep -s 'Workgroup Bridge' /proc/device-tree/model \
  || sed -n 's/Hardware[ \t:]*\(.*\)/\1/p' /proc/cpuinfo )
case $x in
  *'Workgroup Bridge 40N'*) ### arch/arm/mach-at91/board-wb40n.c
    wb=wb40n
    NWBPS=1250000
    ;;
  *'Workgroup Bridge 45N'*) ### arch/arm/mach-at91/board-dt.c
    wb=wb45n
    NWBPS=2000000
    ;;
  *'Workgroup Bridge 50N'*) ### arch/arm/boot/dts/wb50n.dts
    wb=wb50n
    NWBPS=3000000
    ;;
  *) ### architecture unknown
    printf ": %s\n" "${x:-\r}" >&2
    grep -om1 ': ARM' /proc/cpuinfo >&2 \
      || sed -n '/name/{s/model name.*\(: .*\)/\1/p;q}' /proc/cpuinfo >&2
    exit_error "unsupported, must be Summit WB platform"
    ;;
esac

scan_partitions() {
# find settings for imageset a/a, add to get b/b
for x in $(grep -ls nand /sys/class/mtd/*/type)
do
  mtd=${x%%/type}
  read -rst1 name < "$mtd"/name
  read -rst1 size < "$mtd"/size
  mtd=${mtd##/sys/class/mtd/mtd}
  mtd=$((mtd)) || addr=0
  case $name in
    kernel-a) KIA=$( hexify "$addr" ) KIS=$( hexify "$size" ) KIP=$mtd;;
    rootfs-a) RIP=$mtd;;
  esac
  addr=$((addr + size))
done
UBM="$( fw_printenv bootcmd |sed -n 's/.*nand read[ \t]\+\(0[xX][A-Fa-f0-9]\+\).*/\1/p' )"

: $(( ${UBM:-0} + ${KIP:-0} + ${KIA:-0} + ${KIS:-0} + ${RIP:-0} )) \
  || exit_error "cannot determine mapping for kernel/rootfs"
}

parse_flags() {
  case $1 in
  -nv) ## not verbose
    o_verbose=false
    ;;
  -q) ## quiet, no stdout
    o_verbose=false
    o_quiet=true
    exec 1>$X
    ;;
  -f) ## force image overwriting
    o_force=true
    ;;
  -c) ## check md5's of the updated images
    o_check=true
    ;;
  -d) ## don't update, just download the update-list
    o_dnload=true
    ;;
  -x*) ## exit after update, disable notify|transfer|reboot '-x[ntr]*'
    [ -z "${1/-x}" ] || [ x = "${1/*n*/x}" ] && x_notify=false
    [ -z "${1/-x}" ] || [ x = "${1/*t*/x}" ] && x_transfer=false
    [ -z "${1/-x}" ] || [ x = "${1/*r*/x}" ] && x_reboot=false
    ;;
  *) # not a flag
    return 1
  esac
}

# flags/options/switches
while [ -n "$1" ]
do
  case $1 in
  --usage) ## see detailed usage info and examples
    show_usage_info $2
    exit 0
    ;;

  --show) ## show the image md5's in flash for comparison
    echo "$wb - md5's" ${tm:+\[testmode\]}
    printf "  u-boot_env:\n"
    fw_printenv |sed '/^md5_/!d;s/md5_\(.*\)=\(.*\)/    \2  \1/'
    echo
    echo "  ${2:-$FWUL}:" "$(test -s "${2:-$FWUL}" || echo n/a)" || exit 1
    sed -e '/[0-9a-f]\{32\}/!d;s/\([^ ]\+\)\///' \
        -e 's/\(^[ #]*\)\([^ ].*bin\)[ #]*\([0-9a-f]\{32\}\)/ \3  \2/' \
        -e 's/^[ #]*\(.*bin\)\(.*\)/    \1/' ${2:-$FWUL} 2>$X
    echo
    exit 0
    ;;

  --url) ## specify images server link for a local update-list
    test -n ${isl:=${2%/}}"" && shift \
      || exit_error "specify images server link for a local update-list"
    ;;

  --tm*) ## enable persistent testmode, or disable with '--tm off'
    [ "off" = "$2" ] && rm -fv $TMF || { mkdir -p ${TMF%/*}; echo $2 >$TMF; }
    exec $0 --
    ;;

  --n*) ## notify remote via udp '--n <addr:port> <status> [<message>]'
    server=$2
    if [ $# -gt 2 ] && [ ":" = "${server/*:*/:}" ]
    then
      printf "\rNotifying update configuration server %s : %s\n" "$2" "$3"
      busybox nc -u "$server" -e echo "$(${NS_FORMAT}_notification "$3" "$4")" && exit 0
      echo "  ...failed tx: $server"
    fi
    exit 1
    ;;

  --|--version) ## affirm executable, version and mode
    echo $SELF v$VERSION ${tm:+\[testmode\]}
    exit 0
    ;;

  --help|-h) # quick help
    printf "Flags:  \t\t\t(*asterisk denotes variations of a flag/option)\n"
    sed -n '/^parse_fla/,/^ esac/s/\(^  -[a-z*]\+\).*) ## \(.*\)/  \1   \2/p' $0
    printf "Options:\n"
    sed -n '/^#.*options/,/^ esac/s/\(^  --[a-z*]*\).*) ## \(.*\)/\1    \2/p' $0
    printf "Usage:\n  fw_update [flags..] [option|<path/to/fwul>]\n"
    exit 0
    ;;

  -nv|-[qfcd]|-x*) # stow optional flags
    [ "-q" = "$1" ] && o_verbose=false
    fls=${fls:+$fls }${1}
    ;;

  -*) # invalid option/flag, raise
    exit_error "unknown option/flag or mode specified: [$1]"
    ;;

  *) # remaining arg is url/path/to/fwul
    break
  esac
  shift
done
url=$1
shift $#
rm -f /tmp/fwu.*
set -o pipefail

# shellcheck disable=SC2129
wget() {
  if [ -z "$wget_version" ]
  then
    # determine wget version and set appropriate flags
    # ..option --spider is supported by both, but busybox version is crippled
    # ..option -t<retries> is not documented for busybox version
    # ..connect-timeout appears to be unsupported/broken
    # ..error messages are generally different
    case $( command wget --version 2>&1 |sed -n '/^BusyBox\|^GNU/s/\ .*//p' ) in
      BusyBox) wget_version=bb; wget_opt='-T4 -t1';;
      GNU) wget_version=gnu; wget_opt='-T4 -t1 -nv --no-check-certificate';;
      *) exit_error "wget utility is required";;
    esac
  fi
  # workaround for spider mode using gnu version requires verbosity override
  [ "$1" = "--spider" ] && [ "$wget_version" = "gnu" ] && wget_v=-v || wget_v=

  command wget ${wget_opt} ${wget_v} "$@"
} 2>>"$FWU_ERR"

copy() {
  # args: <src> -O <dst>
  cat "$1" >"$3"
} 2>>"$FWU_ERR"

# assume remote
test -z "$url" \
  && { [ fwul = "${isl/*.txt/fwul}" ] && url=$isl; isl=${isl/*.txt}; }
  ## use the images-server-link as url if contains the fwul, then trim

# assume local
test -z "$url" \
  && { url=$(pwd)/${FWUL##*/}; [ -f "$url" ] || url=${FWUL}; }
  ## attempt to guess local path for the fwul when not given

# download/copy the firmware-update-list
if [ remote = "${url/*:*/remote}" ]
then
  # an optional notify-server-address-port
  # may be appended to the url as:
  #     ?nsap=<host>[:<port>]
  nsap=${url#*\?nsap=}; nsap=${nsap##*$host*}
  url=${url%%\?*}

  test fwul = "${url/*.txt/fwul}" \
    || exit_error "firmware-update-list required, try '--usage'"

  verbose true "Downloading '${url##*/}' from $host to $FWUL"
  rm -f $FWUL
  wget "$url" -O $FWUL \
    || exit_error "could not retrieve \"${url##*/}\""

else
  # assuming fwul path to be of a mounted filesystem
  # look for and copy the fwul to /tmp
  [ -d "$url" ] && url=${url%/}/${FWUL##*/}
  [ -f "$url" ] || exit_error "firmware-update-list? ${url##*/}"
  if [ "$url" != "$FWUL" ]
  then
    verbose true "Copying '${url##*/}' from ${url%/*}/ to $FWUL"
    copy "$url" -O $FWUL
  fi
fi
test -s "$FWUL" \
  || exit_error "zero-length file: $FWUL"

# process any flags; given via cmdline preferred over fwul
flags=$( sed -n '/^ *fl[ags]* /{s/.*fl[ags]* //p;q}' $FWUL )
for f in ${fls:-$flags}; do parse_flags $f; done

# bail if set option download for remote fwul
test remote = "${url/*:*/remote}" \
  && ${o_dnload:-false} \
  && exit 0

verbose true "Processing firmware-update-list"
# convert from older format if necessary
if grep -q ".*\.bin\ \+[0-9a-f]\{32\}" $FWUL
then
  sed -e '/[0-9a-f]\{32\}/{s/ *\([^ #]\+\)\///}' \
      -e '/[0-9a-f]\{32\}/{s/ *\([^ #]\+\) *\([0-9a-f]\{32\}\)/\2  \1/}' \
      -e 's/#\+ */# /;s/^[^ #] */  &/' \
      -i $FWUL && txt="*"
fi

# firmware-update-list
if [ -s "$FWUL" ]
then
  ## confirm target wb?? match to update upon given version-tag
  vt=$( sed -n '1s/^[# ]*\([^ ]*wb50[^ ]\+\)/\1/p' $FWUL )
  if [ -n "$vt" ]; then
  case "$vt" in
    *"$wb"*) ;; # $wb found in $vt, continue
    *) exit_error "aborted, $wb update mismatch: $vt" ;;
  esac
  txt=$(printf "%s\n  ...updating to %s" "$txt" "$vt")
  fi

  ## parse md5, name, length and check if absolute url/path or convert
  set -- $( sed -n "/^[^#] *[0-9a-f]\{32\}\ .*${AT91BS_IMG}/p" $FWUL )
  eval AT91BS_MD5="$1" AT91BS_URL="$2" AT91BS_LEN="${3:-0}"
  test -n "${2}" && [ "$(echo "$2" | cut -c1)" != "/" ] && [ "${2/*:*/:}" != ":" ] \
    && AT91BS_URL=${isl:-${url%/*}}/${2/^.\/}

  ## parse md5, name, length and check if absolute url/path or convert
  set -- $( sed -n "/^[^#] *[0-9a-f]\{32\}\ .*${U_BOOT_IMG}/p" $FWUL )
  eval U_BOOT_MD5="$1" U_BOOT_URL="$2" U_BOOT_LEN="${3:-0}"
  test -n "${2}" && [ "$(echo "$2" | cut -c1)" != "/" ] && [ "${2/*:*/:}" != ":" ] \
    && U_BOOT_URL=${isl:-${url%/*}}/${2/^.\/}

  ## parse md5, name, length and check if absolute url/path or convert
  set -- $( sed -n "/^[^#] *[0-9a-f]\{32\}\ .*${KERNEL_IMG}/p" $FWUL )
  eval KERNEL_MD5="$1" KERNEL_URL="$2" KERNEL_LEN="${3:-0}"
  test -n "${2}" && [ "$(echo "$2" | cut -c1)" != "/" ] && [ "${2/*:*/:}" != ":" ] \
    && KERNEL_URL=${isl:-${url%/*}}/${2/^.\/}

  ## parse md5, name, length and check if absolute url/path or convert
  set -- $( sed -n "/^[^#] *[0-9a-f]\{32\}\ .*${ROOTFS_IMG}/p" $FWUL )
  eval ROOTFS_MD5="$1" ROOTFS_URL="$2" ROOTFS_LEN="${3:-0}"
  test -n "${2}" && [ "$(echo "$2" | cut -c1)" != "/" ] && [ "${2/*:*/:}" != ":" ] \
    && ROOTFS_URL=${isl:-${url%/*}}/${2/^.\/}

  ## parse other options
  shell=$( sed -n '/^ *sh[ell]* /{s/.*sh[ell]* //p;q}' $FWUL )

  ## parse/copy transfer-list items to file
  sed -n '/transfer-list/,/^$/p' $FWUL >>"$FWU_TRANSFER_LIST"
else
  exit_error "firmware-update-list error"
fi
mv $FWUL $FWUL~ 2>$X
verbose true "$txt"

# foreach set default if unset
o_verbose=${o_verbose:-true}
o_quiet=${o_quiet:-false}
o_force=${o_force:-false}
o_check=${o_check:-true}
x_notify=${x_notify:-true}
x_transfer=${x_transfer:-true}
x_reboot=${x_reboot:-true}

# if using check option, ensure nanddump exists
if $o_check; then
  command -v nanddump >/dev/null 2>&1 || exit_error "nanddump not found"
fi

# set/check env tool
fw_printenv=fw_printenv
fw_setenv=$tm\ fw_setenv
if ! $fw_printenv >$X
then
  [ -f /etc/fw_env.config ] \
  || txt="fw_printenv support missing: /etc/fw_env.config"
  exit_error "$txt"
fi
fw_select=$tm\ fw_select

# check for a previous pending update
eval "$( $fw_printenv -n updated_% 2>$X \
      | grep -o 'at91bs=.\|u_boot=.\|kernel=.\|rootfs=.' )"
if [ -n "$at91bs$u_boot$kernel$rootfs" ]
then
  echo "Previous update (pending) detected:"
  $fw_printenv |sed -e '/md5_/!d' \
                    -e "${at91bs:+;s/at91bs/1&/p}" \
                    -e "${u_boot:+;s/u-boot/2&/p}" \
                    -e "${kernel:+;s/kernel-$kernel/3&/p}" \
                    -e "${rootfs:+;s/rootfs-$rootfs/4&/p}" -n \
               |sort \
               |sed 's/md5_[1234]/      /;s/=/\t/'
  # revert?
  if ! $o_force
  then
    ask "Proceed?" 5 || exit_error "need to reboot"
  fi
  echo "  ...proceeding"
  fw_select -- >$X 2>&1 \
    || exit_error "...fw_select required to revert kernel/rootfs-a/b swap"

  if [ -n "$kernel" ]
  then
    printf "Reverting kernel-a/b swap\n  ..."
    if [ "$kernel" != a ]; then
      $fw_select kernel-a
    else
      $fw_select kernel-b
    fi
  fi
  if [ -n "$rootfs" ]
  then
    printf "Reverting rootfs-a/b swap\n  ..."
    if [ "$rootfs" != a ]; then
      $fw_select rootfs-a
    else
      $fw_select rootfs-b
    fi
  fi
  eval at91bs= u_boot= kernel= rootfs=
fi

bootcmd_x() {
  [ -z "$UBM" ] && scan_partitions

  # parse formatted kernel-image-address and also copy any boot commands
  eval $( BC_kia=; BC_boot=; F='0x[0-9A-Fa-f]*'; $fw_printenv -n bootcmd \
        |sed -n "s/nand read $F \($F\) $F[; ]*\(.*\)/BC_kia=\1 BC_boot='\2'/p" )

  if [ -z "$BC_kia" ]
  then
    exit_error "incompatible bootcmd set in u-boot_env, use fw_select"
  fi

  BC_kia=$( hexify "$BC_kia" )

  set -- $(fw_printenv -n bootargs)
  for x in "$@"; do
    case "$x" in
      fips=*)
        fips=${x#*=}
        case $fips in [0-1]) ;; *) fips=0 ;; esac
        ;;

      fips_wifi=*)
        fips_wifi=${x#*=}
        case $fips_wifi in [0-1]) ;; *) fips_wifi=0 ;; esac
        ;;
    esac
  done

  return 0
}

kernel_x() {
  # report the kernel partition booted from... (pseudo-static)
  if x=0 bootcmd_x
  then
    # shellcheck disable=SC3039
    if iszero $((BC_kia-KIA))
    then
      let x=$KIP
    else
      let x=$KIP+1
    fi
  fi
  echo "$x"
}

rootfs_x() {
  # report the rootfs partition being used... (actual)
  sed -n 's/.*ubi.mtd=\(.\).*/\1/p' /proc/cmdline
}

# special functions to evaluate arithmetic expressions
# shellcheck disable=SC3039
iszero() { ! let ${1:-0} && return 0 || return 1; }
# shellcheck disable=SC3039
hexify() { let x=${1:-0}; printf "0x%08x" "$x"; }

get_file_md5() {
  file="$1"
  [ -f "$file" ] || return 1
  md5sum "$file" | awk '{print $1}'
  unset file
}

assert_image() {
  # args: <image_name_var> <label>
  sz=
  src=
  img_name=${1}
  img_is_remote=false
  img_downloaded=false
  echo "${tm:+\n}Checking $2"
  : >"$FWU_ERR"
  eval src=\$"${1}"_URL
  test -n "$src" \
    || { echo - update n/a; return 1; }

  # determine if image file is accessible
  if [ remote = "${src/*:*/remote}" ]
  then
    # check image file is really available
    # firstly try to get file info via spider
    # fallback with read/count method on failure
    #
    #==> SIZE kernel.bin ... 1782232 .....ftp method
    #Length: 24133632 (23M) [application/octet-stream] .....http method
    #
    case $src in
    http*)
      wget --spider "$src" 2>>"$FWU_ERR" && \
        sz=$( sed -n 's/Length: \([0-9]*\).*/\1/p' "$FWU_ERR" )
      ;;
    ftp*)
      wget --spider "$src" 2>>"$FWU_ERR"
      sz=$( sed -n 's/.*SIZE.* \([0-9]*\)$/\1/p' "$FWU_ERR" )
      ;;
    esac

    if [ -z "$sz" ] ;  then
      # try reading file when length n/a via wc as a last resort
      eval sz=\$"${1}"_LEN || sz=$( wget -q -O - "$src" |wc -c )
    fi
    img_is_remote=true
  else
    # method local
    if [ -s "$src" ]
    then
      # get file info for method local:
      eval sz=\$"${1}"_LEN || sz=$( wc -c < "$src" )
    fi
  fi
  sz=$((sz+0)) \
    || { printf "file n/a\n\t%s\n" "$src";
         grep -s . "$FWU_ERR"; errors++; return 3; }

  eval md5=\$"${1}"_MD5
  test -n "$md5" \
    || { echo - md5sum n/a; errors++; return 3; }

  # bootstrap and uboot images do not have backup slots
  # download and check md5 sum before flashing the images
  if [ "$img_is_remote" = true ] && \
   { [ "$img_name" = AT91BS ] || [ "$img_name" = U_BOOT ]; }; then
    rm -f "$TMP_DL"
    echo "Download and verify $img_name"
    if ! wget -O "$TMP_DL" "$src" 2>>"$FWU_ERR"; then
      exit_error "ERROR: Failed to download $src"
    fi

    dl_md5=$(get_file_md5 "$TMP_DL")
    if [ "$dl_md5" != "$md5" ]; then
      exit_error "ERROR: MD5 mismatch for $img_name. downloaded $dl_md5 != expected $md5"
    fi
    img_downloaded=true
  fi

  # compare the md5_of_image with the md5_in_flash
  if [ "$md5" = "$(fw_printenv -n md5_"$image" 2>$X)" ]
  then
    if $o_force
    then
      echo - overwriting
    else
      ask "- overwrite?" 9 || return 1
    fi
  else
    echo
  fi
  unset md5 src

  # estimate time from nand-write-bytes-per-sec
  et=$((sz/NWBPS+2))

  return 0
}

flash_image() {
  # args: <image_url> <image_md5>
  #
  img_is_remote=false
  echo "Updating $image"
  : >"$FWU_ERR"
  mtdinfo /dev/"$tp" |grep -q 'writabl.*tru' \
    || { printf "(protected)\n"; return 1; }
  if ${ubifs:=false}
  then
    verbose true "(ubi)"
    ${tm:-:} ubiformat -y /dev/"$tp" -S $sz -f -
    ${tm:-:} \ \ ^--- "$1"
    verbose "  (${et}s) erasing/writing"
    ${tm:+:} ubiformat -y /dev/"$tp" -S $sz -f - < "$FWU_FIFO" 2>&1 \
              |sed 's/.*\r//;s/e  u.*: w/e  \n  w/' >>"$FWU_UBIFS" &
  else
    ${tm:-:} flash_erase -q /dev/"$tp" 0 0
    ${tm:-:} nandwrite -mpq /dev/"$tp"
    ${tm:-:} \ \ ^--- "$1"
    verbose "  (${et}s) erasing"
    ${tm:+:} flash_erase -q /dev/"$tp" 0 0
    verbose "/writing"
    ${tm:+:} nandwrite -mpq /dev/"$tp" < "$FWU_FIFO" &
  fi
  ${tm:+eval wc -c < "$FWU_FIFO" >>"$FWU_ERR" & }
  await $! "$et" _
  if echo "$1" | grep -q '://'; then
    # using a transfer protocol
    txt="image download/flash interrupted"
    if [ $img_downloaded = false ]; then
      img_is_remote=true
      # download the file to the fifo and calculate md5 sum at the same time
      wget -O - "$1" | tee "$FWU_FIFO" | (md5sum | awk '{print $1}' > "$FWU_MD5")
    else
      # the image was already downloaded, copy it to the fifo so it will be written to flash
      copy "$TMP_DL" -O "$FWU_FIFO"
      rm -f "$TMP_DL"
    fi
  else
    # assume local copy
    txt="image copy/flash failed"
    copy "$1" -O "$FWU_FIFO"
  fi
  # shellcheck disable=SC2181
  if [ $? -eq 0 ] ; then
    wait
  else
    exit_error "$txt"
  fi
  # check downloaded image md5sum
  if [ $img_is_remote = true ]; then
    md5=$(cat "$FWU_MD5")
    if [ "$md5" != "$2" ]; then
      exit_error "ERROR: MD5 mismatch for $image. downloaded $md5 != expected $2"
    fi
    unset md5
  fi
  return 0
}

test_image() {
  # args: <image_md5>
  #
  md5=0
  error=0
  if $o_check
  then
    verbose "_reading"
    if $ubifs
    then
      { mkdir -p /mnt/"$tp"
        ts=$( date +"%b %e %H:%M:%S" )
      { dmesg -D; set -x; echo; } 2>$X
      : --- triggered ubifs scan and report ---
        ubiattach -p /dev/"$tp" >$X
      { ubi=$( ubinfo |sed -n '/Present/s/.* \(ubi.\)/\1/p' ); } 2>$X
      { logread |sed -n "/$ts/"',${s/^.*kernel: //p}'; } 2>$X
        ubinfo /dev/"${ubi}"_0 |{ sed '/^[TS]/!d'; } 2>$X
      { echo; } 2>$X
      : --- integrity check using mount ro and crc32 ---
        mount -t ubifs /dev/"${ubi}"_0 -r /mnt/"$tp" \
          && ubicrc32 /dev/"${ubi}"_0
        umount /mnt/"$tp"
        ubidetach -p /dev/"$tp"
      { dmesg -E; set +x; echo; } 2>$X
      } >>"$FWU_UBIFS" 2>&1 &
      await $! "$et" _ && wait
      test -n "$(sed -n '/^State:.*OK/,${/^0x......../p}' "$FWU_UBIFS")"
    else
      md5=$(nanddump -ql $sz --omitoob --bb=skipbad /dev/"$tp" 2>>"$FWU_ERR" \
        | md5sum | awk '{print $1}') || error=$?
      [ "$md5" = "$1" ]
    fi
  fi
  error=$((error + $?))
  if [ $error -eq 0 ]
  then
    echo ^OK
  else
    echo ^FAIL
    grep -s . "$FWU_ERR"
    if $o_check
    then
      echo "  ${md5:-${1//?/ }}  $image"
      echo "  $1  expected"
      x_reboot=false
    fi
  fi
  errors=$((errors + error))
  eval ${tm:+error=0}
  unset md5
  return $error
}

# We assert/flash/test each of the platform image partitions in order:
# bootstrap-loader, uboot-bootloader, linux-kernel-a/b, linux-rootfs-a/b
#
# In testmode, no actual writes to Flash, nor do any extended operations.
${tm:-:} "\n  testmode active\n  ...remove '$TMF'\n     or try: '--tm off'" >&2

# be certain alt_rootfs is unmounted
fw_select --transfer access off >$X

# wr/rd require fifo
mkfifo "$FWU_FIFO" 2>$X

# get info
bootcmd_x

tp=mtd0
image=${AT91BS_IMG%%.*}
if assert_image AT91BS "Bootstrap"
then
  if flash_image "$AT91BS_URL" "$AT91BS_MD5"
  then
    if test_image "$AT91BS_MD5"
    then
      if $fw_setenv md5_"$image" "$AT91BS_MD5"
      then
        $fw_setenv bootstrap
        at91bs=x
      fi
    fi
  fi
fi

if [ "$errors" -gt 0 ]; then
  exit_error "ERROR: Bootloader update failed"
fi

tp=mtd1
image=${U_BOOT_IMG%%.*}
if assert_image U_BOOT "Bootloader"
then
  if flash_image "$U_BOOT_URL" "$U_BOOT_MD5"
  then
    if test_image "$U_BOOT_MD5"
    then
      if $fw_setenv md5_"$image" "$U_BOOT_MD5"
      then
        u_boot=x
      fi
    fi
  fi
fi

if [ "$errors" -gt 0 ]; then
  exit_error "ERROR: U-Boot update failed"
fi

kip_a=$KIP
kip_b=$((KIP+1))
case $(kernel_x) in
  # target alt kernel partition
  "$kip_a") tp=mtd${kip_b}; ab=b; kia=$( hexify $((KIA+KIS)) );;
  "$kip_b") tp=mtd${kip_a}; ab=a; kia=$( hexify "$KIA" );;
esac
image=${KERNEL_IMG%%.*}-$ab
if assert_image KERNEL "Linux Kernel"
then
  if flash_image "$KERNEL_URL" "$KERNEL_MD5"
  then
    if test_image "$KERNEL_MD5"
    then
      if $fw_setenv md5_"$image" "$KERNEL_MD5"
      then
        kernel=$ab
        bootcmd="nand read $UBM $kia $KIS; $BC_boot"
      fi
    fi
  fi
fi

if [ "$errors" -gt 0 ]; then
  exit_error "ERROR: Kernel update failed"
fi

rip_a=$RIP
rip_b=$((RIP+1))
case $(rootfs_x) in
  # target alt rootfs partition
  "$rip_a") tp=mtd${rip_b}; mtdnum=${rip_b}; ab=b;;
  "$rip_b") tp=mtd${rip_a}; mtdnum=${rip_a}; ab=a;;
esac
image=${ROOTFS_IMG%%.*}-$ab ubifs=${UBIFS:-true}
if assert_image ROOTFS "Root Filesystem"
then
  if flash_image "$ROOTFS_URL" "$ROOTFS_MD5"
  then
    if test_image "$ROOTFS_MD5"
    then
      if $fw_setenv md5_"$image" "$ROOTFS_MD5"
      then
        rootfs=$ab
        bootargs="console=ttyS0,115200 loglevel=4 rw rootfstype=ubifs root=ubi0:rootfs ubi.mtd=${mtdnum} init=/usr/sbin/fipsInit.sh fips=${fips:=0} fips_wifi=${fips_wifi:=0}"
        [ "$(fw_select --fips)" = none ] && bootargs=${bootargs/init=\/usr\/sbin\/fipsInit.sh /}
      fi
    fi
  fi
fi

if [ "$errors" -gt 0 ]; then
  exit_error "ERROR: File system update failed"
fi

${tm:-:}
test -n "$shell" \
  && echo shell: \[$shell\] \
  && { test -f "${shell%% *}" && sh - ${shell} || exit_error "failure"; }

[ -z "$nsap" ] && host="${host/:*/}" || host=$nsap
[ ":" = "${host/*:*/:}" ] || host=$host:$NS_PORT
if $x_notify && $0 --n "$host" update_pending
then
: ${uc:=$( busybox nc -w5 -lp${host/*:} 2>$X |sed -n "/^$M/s/${M//?/.} *//p" )}&
  verbose true "Awaiting reply"
  await $! 5 .
  wait
  # shellcheck disable=SC2031
  verbose true "${uc:+OK}"
  # shellcheck disable=SC2031
  $fw_setenv _ucs "${uc}"
fi

echo Syncing
$fw_setenv updated_% \
    "${at91bs:+at91bs=$at91bs} ${u_boot:+u_boot=$u_boot} ${kernel:+kernel=$kernel} ${rootfs:+rootfs=$rootfs} ${host:+host=$host}"

test -n "$rootfs" -a -n "$bootargs" \
  && $fw_setenv bootargs "$bootargs"

test -n "$kernel" -a -n "$bootcmd" \
  && $fw_setenv bootcmd "$bootcmd"

sync

if $x_transfer
then
  if [ -n "$rootfs" ] \
  && fw_select -- >$X 2>&1
  then
    txt="Transfer system files"; false
    if [ -r "$FWU_TRANSFER_LIST" ]
    then
      echo "$txt - found transfer-list"
    else
      if $o_force
      then
        echo "$txt"
      else
        ask "$txt?" 5
      fi
    fi
    test $? -eq 0 \
      && $fw_select --transfer push \
      && echo \ \ ...pushed
  fi
fi

if $x_reboot ; then
  if $o_force ; then
    et=0
  else
    read -t 1 -n 1000
    et=5
    while [ $et -gt 0 ]; do
      et=$((et - 1))
      echo -ne "\rHit any key to avoid reboot in ${et}s ... "
      read -rst 1 -n 1 && break
    done
  fi
  [ $et -ne 0 ] || { echo "reboot" >&2; ${tm:+:} reboot; exit; }
fi

${tm:-:} \\\n$SELF v$VERSION \[testmode\]
[ $errors != 0 ] && echo "Errors:$errors"
echo "Done."
exit $errors
