#! /bin/sh
# SPDX-License-Identifier: LicenseRef-Ezurio-Clause
# Copyright (C) 2024 Ezurio

set -e -o pipefail

notify() {
    [ ! -x /usr/sbin/device_update.sh ] || /usr/sbin/device_update.sh "${1}"
}

die() {
    case "${o_method}" in
    complete*)
        flash_cleanup
        ;;
    esac

    notify failed
    [ -z "${1}" ] || echo "${1}" >&2
    echo "Firmware update failed" >&2
    exit 1
}

usage() {
    cat << --EOF--
"Usage: $0: [-m <method>] [-s <side>] [-x value] [-f] [-v] <url>"
    -m - Updated method (full, main, complete, etc) (default: full - NAND/eMMCC, complete - SD)
    -s - Update side (a, b) (default: automatic)
    -x - Extended options (r - no reboot)
    -f - Factory provision mode (default: off)
    -v - Verbose mode (default: off)
    url - URL to update package
          Supported formats:
            '-' - Read from standard input (stdin)
            file:///path/to/file or /path/to/file - Local file
            http://... or https://... - HTTP/HTTPS download
            ftp://... - FTP download
            ssh://[user@]host/path/to/file - SSH/SCP download
            tcp://port or tcp://:port - Listen on TCP port for incoming data
--EOF--
    exit 3
}

[ $# -ge 1 ] || usage

o_verbose=
o_quiet=true
o_restart=true
o_factory=false

# determine update side
# shellcheck source=/dev/null
. /usr/sbin/boot-rootfs.sh || die

getSide
[ "${bootside:?}" = "a" ] && o_side=b || o_side=a

[ "${rootDevType:?}" = "SD" ] && run_on_sd=true || run_on_sd=false

${run_on_sd} && o_method=complete || o_method=full

if grep -qF '"ubi"' /proc/mtd 2>/dev/null; then
    # shellcheck source=/dev/null
    . /usr/bin/ubi_update_support.sh
else
    # shellcheck source=/dev/null
    . /usr/bin/emmc_update_support.sh
fi

while getopts m:s:x:fv name; do
    case ${name} in
    m)  o_method=${OPTARG} ;;
    s)  o_side=${OPTARG} ;;
    x)  case "${OPTARG}" in
            *r*) o_restart=false ;;
        esac ;;
    f)  o_factory=true ;;
    v)  o_verbose="-v"; o_quiet=false ;;
    ?)  usage ;;
    esac
done
shift $((OPTIND - 1))

url="${1}"

if [ "${o_method}" = complete ]; then
    ${run_on_sd} || die "only 'full' or 'main' update methods supported when booting from NAND/eMMC"
    p_method=${o_method}
else
    ! ${run_on_sd} || die "only 'complete' update method supported when booting from SD card"
    p_method=${o_method}-${o_side}
fi

notify updating

! ${o_quiet} || exec >/dev/null

case "${url}" in
'-') ;;

file://*)
    url="${url#file://}"
    [ -r "${url}" ] || die "File ${url} not found"
    ;;

tcp://*)
    tcp_url="${url#tcp://}"
    # For listen mode, URL format can be tcp://port or tcp://:port
    tcp_port="${tcp_url##*:}"
    [ -z "${tcp_port}" ] && tcp_port="${tcp_url}"
    [ -n "${tcp_port}" ] || \
        die "Invalid TCP URL format (expected tcp://port or tcp://:port)"
    [ -x /bin/nc ] || [ -x /usr/bin/nc ] || die "netcat (nc) not found"
    ;;

*://*)
    case "${url%:*}" in
    http|https|ftp)
        if [ -x /usr/bin/curl ]; then
            /usr/bin/curl -LsfI "${url}" || die "File ${url} not found"
        elif [ -x /usr/bin/wget ]; then
            /usr/bin/wget -T4 -t1 --spider -qO - "${url}" || die "File ${url} not found"
        fi
        ;;
    esac

    if [ -x /usr/bin/curl ]; then
        ! ${o_quiet} || o_dlsilent="-s"
        download_cmd="/usr/bin/curl -Lf ${o_dlsilent} ${url}"
    elif [ -x /usr/bin/wget ]; then
        ! ${o_quiet} || o_dlsilent="-q"
        download_cmd="/usr/bin/wget -T4 -t1 ${o_dlsilent} -O - ${url}"
    else
        die "Download utility not found (need curl or wget)"
    fi
    ;;

*)
    [ -r "${url}" ] || die "File ${url} not found"
    ;;
esac

case "${o_method}" in
complete*)
    flash_cleanup
    ! ${o_factory} || flash_factory_test
    flash_format
    ;;
esac

case "${url}" in
'-')
    # Read from standard input
    swupdate-client -e "stable,${p_method}" ${o_verbose} - || die ""
    ;;

tcp://*)
    # Listen on TCP port
    { 
        nc -l "${tcp_port}" | \
            swupdate-client -e "stable,${p_method}" ${o_verbose} - 
    } || die ""
    ;;

*://*)
    { 
        ${download_cmd} | \
            swupdate-client -e "stable,${p_method}" ${o_verbose} - 
    } || die ""
    ;;

*)
    swupdate-client -e "stable,${p_method}" ${o_verbose} "${url}" || die ""
    ;;
esac

case "${o_method}" in
complete*)
    flash_cleanup 
    ;;
*)
    if [ -x /usr/sbin/migrate_data.sh ]; then
        /usr/sbin/migrate_data.sh || die "Data migrate failed"
    fi
    ;;
esac

sync

notify complete
echo "Firmware update succeeded" >&2

if ${o_restart} && ! ${run_on_sd}; then
    sleep 1
    reboot
fi
